### PR TITLE
New TFN widget

### PR DESCRIPTION
**Pull request by wilsonCernWq**
@Twinklebear You can merge it if you think it is fine !

### CODE REVIEW

**Comment by Twinklebear** [comment]
What changes are made to the tfn lib included with OSPRay? Could we just use the version included with the OSPRay apps?

**Comment by wilsonCernWq** [comment]
For now there aren't too much changes, but I am planing to updates for supporting more complicated control points, such as Gaussian control points

**Comment by Twinklebear** [comment]
Gotcha, in that case it would be good to change the namespace or rename things a bit so we don't run into some conflicts with the existing tfn lib.

**Comment by wilsonCernWq** [comment]
My intention is to minimize the changes we need for existing codes. I hope this small library can eventually replace the one in ospray.

**Comment by Twinklebear** [comment]
Sounds good!

**Pull request merged**
